# Generated by Django 2.1 on 2018-08-19 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.SmallIntegerField(choices=[(0, 'Downloading video...'), (1, 'Converting video...'), (2, 'Finished'), (3, 'Cleaned')], default=0)),
                ('youtube_id', models.CharField(max_length=128)),
                ('youtube_title', models.CharField(max_length=128)),
                ('youtube_thumbnail', models.CharField(max_length=255)),
                ('youtube_duration', models.IntegerField()),
                ('exception', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
