# Generated by Django 2.1 on 2018-08-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt2m', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='task_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
