# Generated by Django 2.1 on 2018-08-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt2m', '0002_download_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='exception',
            new_name='error',
        ),
        migrations.AlterField(
            model_name='download',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Downloading video...'), (1, 'Converting video...'), (2, 'Finished'), (3, 'ERROR'), (4, 'Cleaned')], default=0),
        ),
    ]
