# Generated by Django 2.1 on 2018-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt2m', '0003_auto_20180819_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='cut_end',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='cut_start',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
